# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogUserVehicles.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserVehicleDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(815, 543)
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(-3, -5, 821, 551))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("../photos/imgonline-com-ua-Blur-2l4fVmT8e17N.jpg"))
        self.background.setObjectName("background")
        self.upperBack = QtWidgets.QLabel(Dialog)
        self.upperBack.setGeometry(QtCore.QRect(-3, -5, 821, 81))
        self.upperBack.setStyleSheet("color: grey; background-color: rgba(255,255,255,100)")
        self.upperBack.setText("")
        self.upperBack.setObjectName("upperBack")
        self.returnButton = QtWidgets.QPushButton(Dialog)
        self.returnButton.setGeometry(QtCore.QRect(670, 10, 131, 51))
        self.returnButton.setObjectName("returnButton")
        self.searchText = QtWidgets.QLineEdit(Dialog)
        self.searchText.setGeometry(QtCore.QRect(20, 20, 231, 31))
        self.searchText.setStyleSheet("color: grey; background-color: rgba(255,255,255,150)")
        self.searchText.setObjectName("searchText")
        self.searchButton = QtWidgets.QPushButton(Dialog)
        self.searchButton.setGeometry(QtCore.QRect(270, 10, 131, 51))
        self.searchButton.setObjectName("searchButton")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(15, 91, 791, 441))
        self.tableView.setStyleSheet("color: grey; background-color: rgba(255,255,255,200)\n"
"")
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.returnButton.setText(_translate("Dialog", "Назад"))
        self.searchText.setPlaceholderText(_translate("Dialog", "                             VIN"))
        self.searchButton.setText(_translate("Dialog", "Поиск"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_UserVehicleDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
