# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogUni.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(815, 543)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-3, -5, 821, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("dialogs/photos/imgonline-com-ua-Blur-2l4fVmT8e17N.jpg"))
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(40, 110, 541, 371))
        self.tableView.setStyleSheet("background-color: rgba(255, 255, 255, 150)")
        self.tableView.setObjectName("tableView")
        self.upperBackground = QtWidgets.QToolButton(Dialog)
        self.upperBackground.setGeometry(QtCore.QRect(-5, -9, 821, 81))
        self.upperBackground.setText("")
        self.upperBackground.setObjectName("upperBackground")
        self.buttonSearch = QtWidgets.QPushButton(Dialog)
        self.buttonSearch.setGeometry(QtCore.QRect(270, 20, 131, 31))
        self.buttonSearch.setObjectName("buttonSearch")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(670, 10, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 231, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(90, 117, 237)")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonSearch.setText(_translate("Dialog", "Поиск"))
        self.pushButton.setText(_translate("Dialog", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
