# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, 0, 881, 651))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("photos/imgonline-com-ua-Blur-2l4fVmT8e17N.jpg"))
        self.background.setObjectName("background")
        self.upperBack = QtWidgets.QToolButton(self.centralwidget)
        self.upperBack.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.upperBack.setText("")
        self.upperBack.setObjectName("upperBack")
        self.buttonAutoDamage = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAutoDamage.setGeometry(QtCore.QRect(10, 10, 241, 51))
        self.buttonAutoDamage.setObjectName("buttonAutoDamage")
        self.buttonInsurance = QtWidgets.QPushButton(self.centralwidget)
        self.buttonInsurance.setGeometry(QtCore.QRect(270, 10, 251, 51))
        self.buttonInsurance.setObjectName("buttonInsurance")
        self.buttonAccident = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAccident.setGeometry(QtCore.QRect(540, 10, 251, 51))
        self.buttonAccident.setObjectName("buttonAccident")
        self.lowerBack = QtWidgets.QToolButton(self.centralwidget)
        self.lowerBack.setGeometry(QtCore.QRect(10, 460, 781, 91))
        self.lowerBack.setText("")
        self.lowerBack.setObjectName("lowerBack")
        self.adminLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminLabel.setGeometry(QtCore.QRect(50, 480, 711, 51))
        self.adminLabel.setObjectName("adminLabel")
        self.buttonQuit = QtWidgets.QPushButton(self.centralwidget)
        self.buttonQuit.setGeometry(QtCore.QRect(690, 420, 100, 32))
        self.buttonQuit.setObjectName("buttonQuit")
        self.rightBackground = QtWidgets.QToolButton(self.centralwidget)
        self.rightBackground.setGeometry(QtCore.QRect(210, 90, 371, 221))
        self.rightBackground.setText("")
        self.rightBackground.setObjectName("rightBackground")
        self.shortInfoLabel = QtWidgets.QLabel(self.centralwidget)
        self.shortInfoLabel.setGeometry(QtCore.QRect(210, 90, 371, 41))
        self.shortInfoLabel.setObjectName("shortInfoLabel")
        self.accNumText = QtWidgets.QLabel(self.centralwidget)
        self.accNumText.setGeometry(QtCore.QRect(220, 140, 301, 31))
        self.accNumText.setObjectName("accNumText")
        self.accAmountInput = QtWidgets.QLabel(self.centralwidget)
        self.accAmountInput.setGeometry(QtCore.QRect(420, 140, 81, 31))
        self.accAmountInput.setText("")
        self.accAmountInput.setObjectName("accAmountInput")
        self.accCityText = QtWidgets.QLabel(self.centralwidget)
        self.accCityText.setGeometry(QtCore.QRect(220, 190, 251, 41))
        self.accCityText.setObjectName("accCityText")
        self.accCityInput = QtWidgets.QLabel(self.centralwidget)
        self.accCityInput.setGeometry(QtCore.QRect(460, 190, 121, 41))
        self.accCityInput.setText("")
        self.accCityInput.setObjectName("accCityInput")
        self.dateText = QtWidgets.QLabel(self.centralwidget)
        self.dateText.setGeometry(QtCore.QRect(220, 250, 111, 21))
        self.dateText.setObjectName("dateText")
        self.dateInput = QtWidgets.QLabel(self.centralwidget)
        self.dateInput.setGeometry(QtCore.QRect(340, 250, 161, 31))
        self.dateInput.setText("")
        self.dateInput.setObjectName("dateInput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Accident Manager"))
        self.buttonAutoDamage.setText(_translate("MainWindow", "Информация по ущербу авто"))
        self.buttonInsurance.setText(_translate("MainWindow", "Страховые компании"))
        self.buttonAccident.setText(_translate("MainWindow", "Информация о ДТП"))
        self.adminLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:700;\">Вход совершен от имени пользователя</span></p></body></html>"))
        self.buttonQuit.setText(_translate("MainWindow", "Выйти"))
        self.shortInfoLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:700;\">Краткая сводка</span></p></body></html>"))
        self.accNumText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Общее количество ДТП:</span></p></body></html>"))
        self.accCityText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Лучшая страховая компания:</span></p></body></html>"))
        self.dateText.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Актуально на:</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_UserMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
